# Generated by Django 2.2.7 on 2019-12-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numero_borradores',
            field=models.IntegerField(default=0),
        ),
    ]
