# Generated by Django 2.2.7 on 2019-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_profile_numero_borradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'ALUMNO'), (1, 'INSTRUCTOR'), (2, 'MIEMBRO DEL CONSEJO ACADÉMICO')], null=True),
        ),
    ]
