# Generated by Django 2.1.3 on 2019-12-04 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.DurationField()),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('financiamiento', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('costo', models.FloatField()),
                ('aula', models.CharField(max_length=20)),
                ('cupo', models.SmallIntegerField()),
                ('estado', models.SmallIntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=40)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Instructor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(to='main.Curso'),
        ),
    ]
