<<<<<<< HEAD
# Generated by Django 3.0 on 2019-12-06 22:41
=======
# Generated by Django 2.1.3 on 2019-12-06 23:24
>>>>>>> 630e89a5241df3cb5ebc2495e80665cc75d47a40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=40)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('duracion', models.SmallIntegerField(blank=True, null=True)),
=======
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.DurationField(blank=True, null=True)),
>>>>>>> 630e89a5241df3cb5ebc2495e80665cc75d47a40
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('financiamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('aula', models.CharField(blank=True, max_length=20, null=True)),
                ('cupo', models.SmallIntegerField(blank=True, null=True)),
                ('estado', models.SmallIntegerField(blank=True, choices=[(0, 'Planeación'), (1, 'En proceso de aprobación'), (2, 'Aprobado'), (3, 'No aprobado'), (4, 'En proceso de impartición'), (5, 'Terminado')], max_length=6, null=True)),
<<<<<<< HEAD
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Instructor')),
=======
                ('slug', models.SlugField()),
>>>>>>> 630e89a5241df3cb5ebc2495e80665cc75d47a40
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=40)),
                ('cursos', models.ManyToManyField(to='main.Curso')),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.AddField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Instructor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(to='main.Curso'),
        ),
>>>>>>> 630e89a5241df3cb5ebc2495e80665cc75d47a40
    ]
