# Generated by Django 2.1.3 on 2019-12-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='aula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupo',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.SmallIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicial',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='financiamiento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Instructor'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
