# Generated by Django 2.1.3 on 2019-12-04 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191203_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='aula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupo',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.SmallIntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='financiamiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Instructor'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
