# Generated by Django 3.0 on 2019-12-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191203_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Planeación'), (1, 'En proceso de aprobación'), (2, 'Aprobado'), (3, 'No aprobado'), (4, 'En proceso de impartición'), (5, 'Terminado')], max_length=6, null=True),
        ),
    ]
