# Generated by Django 3.0 on 2019-12-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='caracter',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='curso',
            name='obj_general',
            field=models.TextField(blank=True, null=True),
        ),
    ]
