# Generated by Django 2.1.3 on 2019-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='pdf',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
