# Generated by Django 2.2.7 on 2019-12-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
