# Generated by Django 3.0 on 2019-12-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20191210_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='departamento',
            field=models.CharField(max_length=40),
        ),
    ]
