# Generated by Django 3.0 on 2019-12-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20191210_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='obj_particular',
            field=models.TextField(blank=True, null=True),
        ),
    ]
