# Generated by Django 2.2.7 on 2019-12-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20191208_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
