# Generated by Django 2.1.3 on 2019-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20191210_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/constancias'),
        ),
    ]
