# Generated by Django 3.0 on 2019-12-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20191210_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='cupo',
        ),
        migrations.AddField(
            model_name='curso',
            name='cupo_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='cupo_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
