# Generated by Django 2.2.7 on 2019-12-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_auto_20191210_0521'),
        ('curso', '0005_auto_20191210_2023'),
    ]

    operations = [
    ]
