# Generated by Django 2.2.7 on 2019-12-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20191210_2023'),
        ('curso', '0006_auto_20191210_0521'),
    ]

    operations = [
    ]
