# Generated by Django 2.1.3 on 2019-12-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20191210_2023'),
        ('curso', '0006_auto_20191210_0521'),
    ]

    operations = [
    ]
