# Generated by Django 3.0 on 2019-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_merge_20191211_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='calificacionCurso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='calificacionInstructor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='sugerenciaCurso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='sugerenciaInstructor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='caracter',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='curso',
            name='infraestructura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='constancias/'),
        ),
    ]
