# Generated by Django 2.2.7 on 2019-12-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_auto_20191212_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='departamento',
            field=models.CharField(default='Matematicas', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(default='Ciencias exactas y naturales', max_length=60, null=True),
        ),
    ]
