# Generated by Django 2.2.7 on 2019-12-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0009_auto_20191212_2023'),
        ('curso', '0008_auto_20191212_0603'),
    ]

    operations = [
    ]
