# Generated by Django 2.2.7 on 2019-12-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0010_merge_20191212_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='calficacion_curso',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
